feat(아티스트): 아티스트 관리 페이지
HandyBus/handybus-admin-web-latest pull request #3
Opened 2024-11-27 14:45 UTC by stonechoe

## 개요

## 변경사항
어떤 변경 사항이 있나요?
* tanstack table 및 zod 라이브러리 추가
* 간단한 아티스트 설정 페이지를 만들었습니다.
* tanstack table: 어드민 페이지는 데이터를 볼 일이 많으므로 정렬/검색 등의 기능 도입을 염두해서 tanstack table을 사용했습니다.
* zod: 어드민 페이지임으로 오류에 더 강건하게 만들기 위해 schema를 이용해 확인하도록 했습니다.

https://github.com/user-attachments/assets/635453ae-5a37-43b4-bdea-d1620703c710

## PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.

- [x] 커밋 메시지 컨벤션에 맞게 작성했습니다. Commit message convention 참고
- [ ] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

2024-12-03 09:04 UTC, stonechoe commented
@gw-lim @joonseong11 오늘 피알 보느라 고생 많으십니다 이것도 가능하시면......…ㅎㅎㅎㅎ

2024-12-03 09:41 UTC, gw-lim requested changes

2024-12-03 09:41 UTC, gw-lim commented on src/app/artists/(home)/page.tsx
> +    );
여기는 instance가 아닌 fetch로 하신 이유가 따로 있으신가요?
또한 어떠한 경우에 서버 액션으로 빼시는지 궁금합니다. 현재 제가 봤을 때는 클라이언트 사이드에서 요청을 보내야할 때는 서버 액션으로 뺴시는 것 같은데 통일성과 api 재활용성이 걱정되어서요!

2024-12-03 09:41 UTC, gw-lim commented on src/app/artists/(home)/page.tsx
> +    const a = await getArtists();
여기 변수명이 변경되지 않은 것 같아요!

2024-12-03 09:41 UTC, gw-lim commented on src/app/artists/new/page.tsx
> +  const handleSubmit: React.FormEventHandler<HTMLFormElement> = useCallback(
`React.`이 아닌 직접 import해주시면 감사하겠습니다!

2024-12-03 09:41 UTC, gw-lim commented on src/app/artists/new/page.tsx
> +        })();
여기서 await와 then을 혼용해서 사용하신 이유가 있으신가요?

2024-12-03 09:41 UTC, gw-lim commented on src/components/link/BlueLink.tsx
어드민 페이지에서는 프롭을 따로 받지 않는 컴포넌트는 tailwind styled components로 선언하는 것으로 이해하겠습니다!

2024-12-03 09:41 UTC, gw-lim commented on src/components/text-input/TextInput.stories.tsx
어드민 페이지에서도 스토리북이 필요한지 이야기해보면 좋을것 같네요...

2024-12-03 12:16 UTC, stonechoe commented on src/app/artists/(home)/page.tsx
> +    );
앗 이유가 있는건 아니고 바꾸는걸 깜빡했습니다 ㅜㅜ axios 사용하도록 바꿔놓을게요!

2024-12-04 09:05 UTC, stonechoe commented on src/components/text-input/TextInput.stories.tsx
넵. 이 컴포넌트는 기존 레포지토리에서 가져온거라 스토리북도 가져오긴 했는데요, 어드민 페이지에 꼭 필요하지는 않을 것 같네요. 우선 지우겠습니다. 논의해봐요

2024-12-04 09:41 UTC, stonechoe commented
@joonseong11 리뷰 부탁드립니다
@gw-lim 수정 요청 사항 확인하시고 다시 리뷰 부탁드립니다

2024-12-04 09:53 UTC, joonseong11 approved these changes
고생하셨어요 ㅎㅎ몇가지 질문을 남겼어요 보시고 댓글 남겨주시면 감사하겠습니다

2024-12-04 09:53 UTC, joonseong11 commented on src/types/artist.type.ts
> +export type ArtistType = z.infer<typeof ArtistSchema>;
zod 를 사용하니 원하는 스키마를 그리고, 해당하는 추론 타입을 쉽게 가져올 수 있네요

2024-12-04 09:53 UTC, joonseong11 commented on src/app/artists/(home)/page.tsx
> +    return Promise.reject(e);
여기서 Promise.reject를 사용하면 어떤 이점을 얻을 수 있나요?
global-error.tsx에서 바로 에러를 캐치할 수 있는 거 같은데 맞나요?

2024-12-04 09:53 UTC, joonseong11 commented on src/app/artists/(home)/components/ArtistTable.tsx
호... tanstack table을 사용한 코드라 낯설긴한데 이걸 사용한 여기 컴포넌트는 tanstack table을 사용하지 않았을 때랑 비교하면 어떤점이 유리한가요?

2024-12-04 09:53 UTC, joonseong11 commented on src/components/text-input/TextInput.stories.tsx
스토리북은 개발단계에서 빠른 ui 테스팅이 필요하시면 쓰시면 될 거 같아요. 여기서는 기존의 컴포넌트를 가져온거라  불필요해보이지만, 추가로 어드민에서 컴포넌트 개선 및 추가가 일어난다면, 사용하시면 되겠습니다 ☺️

2024-12-04 10:16 UTC, stonechoe commented on src/types/artist.type.ts
> +export type ArtistType = z.infer<typeof ArtistSchema>;
네 zod로 해두니 이번에 백엔드 응답이 바뀐것도 검증 오류 나는 것 보고 빠르게 알 수 있어서 좋았네요!

2024-12-04 10:18 UTC, stonechoe commented on src/app/artists/(home)/page.tsx
> +    return Promise.reject(e);
이 코드에서 Promise.reject를 사용했기 때문에 try-catch가 없는 것과 동일한 효과를 냅니다. 원래는 여기서 난 에러를 확인하기 위해 console.error 같은 거로 출력만 찍고 원래 반환값 그대로 리턴해주려고 했는데, console.error를 지우면서 이렇게 된 것 같네요.

2024-12-04 10:19 UTC, stonechoe commented on src/app/artists/(home)/components/ArtistTable.tsx
단순히 보여주기만 하는 용도로는 유리한 점이 없을 수 있지만, tanstack table을 사용하면 정렬/검색/필터링 등 복잡한 데이터 조작을 구현하기 쉬워집니다. 나중에 기능 개선할 것을 염두해두고 사용했어요!

2024-12-04 10:20 UTC, merged